name: Execução Diária - Gerar Página

on:
  schedule:
    - cron: '0 3 * * *'   # Executa diariamente à meia-noite (UTC). Ajuste conforme precisar.
  workflow_dispatch:     # Permite execução manual

jobs:
  run-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Atualizar pip e instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar dependências do Playwright e Chromium
        run: |
          # instala libs do SO necessárias e o navegador Chromium
          playwright install-deps || true
          playwright install chromium

      - name: Executar script (rodar apenas uma vez)
        env:
          RUN_ONCE: 'true'
        run: python main.py

      # Passo opcional para depuração — mostra o html gerado no log
      - name: Mostrar docs/index.html (debug)
        if: always()
        run: |
          echo "=== início docs/index.html ==="
          if [ -f docs/index.html ]; then
            sed -n '1,200p' docs/index.html || true
          else
            echo "docs/index.html não encontrado"
          fi
          echo "=== fim docs/index.html ==="

      - name: Commitar e enviar docs/index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # configura usuário de commit
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # adiciona arquivo gerado
          git add docs/index.html || true

          # só commita se houver mudanças
          if ! git diff --staged --quiet; then
            git commit -m "Atualiza página de previsão (gerado pelo Actions) [skip ci]"
            git push
            echo "docs/index.html atualizado e enviado."
          else
            echo "Nenhuma alteração em docs/index.html — nada a commitar."
          fi
